// Package image translates a Modal .image DSL chain into a Dockerfile, builds it,
// and pushes to ECR (spec §13/image). Build once, cache by content digest;
// a rebuild-on-no-change MUST be a cache hit — otherwise it's a leak (§10).
//
// The Dockerfile generation is pure/offline and unit-tested here. The build+push
// (buildkit + ECR) is the only part that touches AWS, and it's cheap (no compute
// launch) — it attaches in build.go.
package image

import (
	"crypto/sha256"
	"fmt"
	"sort"
	"strings"

	"github.com/spore-host/calque/internal/ir"
	"github.com/spore-host/calque/internal/leak"
)

// baseImages maps Modal image bases to concrete Docker base images. For the spike
// we target a CUDA-capable base so the RTX PRO 6000 (g7e) can run the payload.
var baseImages = map[string]string{
	"debian_slim": "nvidia/cuda:12.4.1-runtime-ubuntu22.04",
	// from_registry / from_dockerfile are handled specially (they name their own base)
}

// Spec is the resolved input for a Dockerfile: the IR image plus the worker glue
// calque always adds (the warm runner + warmd + a python with the right version).
type Spec struct {
	Image     ir.Image
	PythonVer string // e.g. "3.11"; empty => image default
	WorkerDir string // in-image path where runner.py + warmd land, e.g. "/opt/calque"
	EntryCmd  string // container entrypoint (warmd invocation); set by exec wiring
}

// Render turns an image chain into Dockerfile text. It walks the DSL steps in
// order so layer semantics match Modal's. Unhandled DSL verbs are emitted as
// comments AND leaked — never silently dropped (a dropped apt_install would make
// the payload fail at runtime in a way that looks like a code bug).
func Render(spec Spec, script string, rep *leak.Report) (string, error) {
	img := spec.Image
	var b strings.Builder

	base, err := resolveBase(img, script, rep)
	if err != nil {
		return "", err
	}
	fmt.Fprintf(&b, "# generated by calque from a Modal .image chain — do not edit\n")
	fmt.Fprintf(&b, "FROM %s\n", base)
	b.WriteString("ENV DEBIAN_FRONTEND=noninteractive\n")

	// Ensure python + pip exist (the CUDA base has none). Kept minimal.
	b.WriteString("RUN apt-get update && apt-get install -y --no-install-recommends \\\n")
	b.WriteString("        python3 python3-pip python3-venv ca-certificates curl && \\\n")
	b.WriteString("    rm -rf /var/lib/apt/lists/*\n")

	for _, step := range img.Steps {
		switch step.Method {
		case "debian_slim", "from_registry", "from_dockerfile", "micromamba":
			// base constructors — already handled by resolveBase
		case "pip_install", "uv_pip_install":
			if len(step.Args) > 0 {
				installer := "pip3 install --no-cache-dir"
				if step.Method == "uv_pip_install" {
					// uv is faster; install it once then use it. Falls back to pip if uv fails.
					b.WriteString("RUN pip3 install --no-cache-dir uv || true\n")
					installer = "uv pip install --system"
				}
				fmt.Fprintf(&b, "RUN %s %s\n", installer, quoteJoin(step.Args))
			}
		case "apt_install":
			if len(step.Args) > 0 {
				fmt.Fprintf(&b, "RUN apt-get update && apt-get install -y --no-install-recommends %s && rm -rf /var/lib/apt/lists/*\n", quoteJoin(step.Args))
			}
		case "run_commands":
			for _, cmd := range step.Args {
				fmt.Fprintf(&b, "RUN %s\n", cmd)
			}
		case "env":
			// env(...) args come through as "KEY=VALUE" strings if literal
			for _, kv := range step.Args {
				fmt.Fprintf(&b, "ENV %s\n", kv)
			}
		case "workdir":
			if len(step.Args) == 1 {
				fmt.Fprintf(&b, "WORKDIR %s\n", step.Args[0])
			}
		default:
			// A DSL verb we don't model. Comment it AND leak it — silent drop would
			// change the runtime environment invisibly (§10).
			fmt.Fprintf(&b, "# UNHANDLED .%s(%s) — see leak report\n", step.Method, quoteJoin(step.Args))
			rep.Addf(leak.PrimImage, leak.KindUnsupportedArg, script, 0,
				"image DSL verb .%s(...) not translated to Dockerfile; environment may differ from Modal", step.Method)
		}
	}

	// Worker glue: the warm runner + warmd supervisor. Copied into the image so
	// the instance runs `warmd` which drives `runner.py` (§6).
	wd := spec.WorkerDir
	if wd == "" {
		wd = "/opt/calque"
	}
	fmt.Fprintf(&b, "COPY runner.py %s/runner.py\n", wd)
	fmt.Fprintf(&b, "COPY warmd %s/warmd\n", wd)
	if spec.EntryCmd != "" {
		fmt.Fprintf(&b, "CMD %s\n", spec.EntryCmd)
	}
	return b.String(), nil
}

func resolveBase(img ir.Image, script string, rep *leak.Report) (string, error) {
	if img.Unresolved || img.Base == "" {
		rep.Add(leak.PrimImage, leak.KindSemanticGap, script, 0,
			"image base unresolved; defaulting to CUDA runtime base — payload deps may be incomplete")
		return baseImages["debian_slim"], nil
	}
	if b, ok := baseImages[img.Base]; ok {
		return b, nil
	}
	// from_registry("nvcr.io/...") names its own base in the first step's args.
	for _, s := range img.Steps {
		if s.Method == "from_registry" && len(s.Args) > 0 {
			return s.Args[0], nil
		}
	}
	rep.Addf(leak.PrimImage, leak.KindUnhandledCase, script, 0,
		"unknown image base %q; defaulting to CUDA runtime base", img.Base)
	return baseImages["debian_slim"], nil
}

// Digest is a stable content hash of the Dockerfile text, used as the ECR tag so
// an identical image is a cache hit (build-once, §10). Same Dockerfile => same tag.
func Digest(dockerfile string) string {
	sum := sha256.Sum256([]byte(dockerfile))
	return fmt.Sprintf("%x", sum)[:16]
}

// quoteJoin renders args as a space-joined, shell-safe list. Package names rarely
// need quoting, but a version spec like "torch==2.4.1" is fine unquoted; anything
// with spaces gets quoted.
func quoteJoin(args []string) string {
	cp := append([]string(nil), args...)
	// stable order only for pip-like package lists where order is immaterial to
	// correctness but matters for a reproducible digest.
	if looksLikePackages(cp) {
		sort.Strings(cp)
	}
	parts := make([]string, len(cp))
	for i, a := range cp {
		if strings.ContainsAny(a, " \t\"'") {
			parts[i] = fmt.Sprintf("%q", a)
		} else {
			parts[i] = a
		}
	}
	return strings.Join(parts, " ")
}

func looksLikePackages(args []string) bool {
	for _, a := range args {
		if strings.ContainsAny(a, "/&|;") { // a shell command, not a package
			return false
		}
	}
	return true
}
