// Package image translates a Modal .image DSL chain into a Dockerfile, builds it,
// and pushes to ECR (spec §13/image). Build once, cache by content digest;
// a rebuild-on-no-change MUST be a cache hit — otherwise it's a leak (§10).
//
// The Dockerfile generation is pure/offline and unit-tested here. The build+push
// (buildkit + ECR) is the only part that touches AWS, and it's cheap (no compute
// launch) — it attaches in build.go.
package image

import (
	"crypto/sha256"
	"fmt"
	"sort"
	"strings"

	"github.com/spore-host/calque/internal/ir"
	"github.com/spore-host/calque/internal/leak"
)

// baseImages maps Modal image bases to concrete Docker base images. For the spike
// we target a CUDA-capable base so the RTX PRO 6000 (g7e) can run the payload.
var baseImages = map[string]string{
	"debian_slim": "nvidia/cuda:12.4.1-runtime-ubuntu22.04",
	// from_registry / from_dockerfile / from_aws_ecr / micromamba are handled
	// specially in resolveBase (they name their own base ref, need a leak about
	// a limitation, or both — §D, calque#84).
}

// micromambaBase is the closest stock equivalent to Modal's Image.micromamba()
// conda-alternative base. No GPU/CUDA variant of this image exists — a GPU
// payload built on it needs its own CUDA install via .apt_install/.run_commands,
// same as it would on Modal's own micromamba() base (calque#84).
const micromambaBase = "mambaorg/micromamba:latest"

// Spec is the resolved input for a Dockerfile: the IR image plus the worker glue
// calque always adds (the warm runner + warmd + a python with the right version).
type Spec struct {
	Image     ir.Image
	PythonVer string // e.g. "3.11"; empty => image default
	WorkerDir string // in-image path where runner.py + warmd land, e.g. "/opt/calque"
	EntryCmd  string // container entrypoint (warmd invocation); set by exec wiring
}

// Render turns an image chain into Dockerfile text. It walks the DSL steps in
// order so layer semantics match Modal's. Unhandled DSL verbs are emitted as
// comments AND leaked — never silently dropped (a dropped apt_install would make
// the payload fail at runtime in a way that looks like a code bug).
func Render(spec Spec, script string, rep *leak.Report) (string, error) {
	img := spec.Image
	var b strings.Builder

	base, err := resolveBase(img, script, rep)
	if err != nil {
		return "", err
	}
	fmt.Fprintf(&b, "# generated by calque from a Modal .image chain — do not edit\n")
	fmt.Fprintf(&b, "FROM %s\n", base)
	b.WriteString("ENV DEBIAN_FRONTEND=noninteractive\n")

	// Ensure python + pip exist (the CUDA base has none). Kept minimal.
	b.WriteString("RUN apt-get update && apt-get install -y --no-install-recommends \\\n")
	b.WriteString("        python3 python3-pip python3-venv ca-certificates curl && \\\n")
	b.WriteString("    rm -rf /var/lib/apt/lists/*\n")

	for _, step := range img.Steps {
		switch step.Method {
		case "debian_slim", "from_registry", "from_dockerfile", "from_aws_ecr", "micromamba":
			// base constructors — already handled by resolveBase
		case "pip_install", "uv_pip_install":
			if len(step.Args) > 0 {
				installer := "pip3 install --no-cache-dir"
				if step.Method == "uv_pip_install" {
					// uv is faster; install it once then use it. Falls back to pip if uv fails.
					b.WriteString("RUN pip3 install --no-cache-dir uv || true\n")
					installer = "uv pip install --system"
				}
				fmt.Fprintf(&b, "RUN %s %s\n", installer, quoteJoin(step.Args))
			}
		case "pip_install_from_requirements":
			// .pip_install_from_requirements("requirements.txt") — the file must be in
			// the build context (a local-path dependency; see A3's staging note). We
			// emit the COPY+install and leak the context requirement so a missing file
			// fails loudly, not silently.
			if len(step.Args) > 0 {
				req := step.Args[0]
				fmt.Fprintf(&b, "COPY %s /tmp/requirements.txt\n", req)
				b.WriteString("RUN pip3 install --no-cache-dir -r /tmp/requirements.txt\n")
				leakLocalContext(rep, script, step.Method, req)
			}
		case "poetry_install_from_file":
			// .poetry_install_from_file("pyproject.toml") — copy the project files and
			// let poetry resolve. Local-path dependency (A3).
			if len(step.Args) > 0 {
				pyproject := step.Args[0]
				fmt.Fprintf(&b, "COPY %s /tmp/pyproject.toml\n", pyproject)
				b.WriteString("RUN pip3 install --no-cache-dir poetry && cd /tmp && poetry install --no-root\n")
				leakLocalContext(rep, script, step.Method, pyproject)
			}
		case "apt_install":
			if len(step.Args) > 0 {
				fmt.Fprintf(&b, "RUN apt-get update && apt-get install -y --no-install-recommends %s && rm -rf /var/lib/apt/lists/*\n", quoteJoin(step.Args))
			}
		case "run_commands":
			for _, cmd := range step.Args {
				fmt.Fprintf(&b, "RUN %s\n", cmd)
			}
		case "dockerfile_commands":
			// Raw Dockerfile lines the user supplied — pass through verbatim, in order.
			for _, line := range step.Args {
				fmt.Fprintf(&b, "%s\n", line)
			}
		case "env":
			// env(...) args come through as "KEY=VALUE" strings if literal
			for _, kv := range step.Args {
				fmt.Fprintf(&b, "ENV %s\n", kv)
			}
		case "workdir":
			if len(step.Args) == 1 {
				fmt.Fprintf(&b, "WORKDIR %s\n", step.Args[0])
			}
		case "entrypoint":
			// .entrypoint([...]) sets the container ENTRYPOINT (exec form).
			if len(step.Args) > 0 {
				fmt.Fprintf(&b, "ENTRYPOINT [%s]\n", jsonArrayJoin(step.Args))
			}
		case "add_local_dir", "add_local_file", "copy_local_dir", "copy_local_file", "add_local_python_source":
			// A3: these reference LOCAL paths that must be staged into the build
			// context. We render a COPY (src -> dst) but the src is only valid if the
			// caller stages it; we can't stage from here, so we leak the requirement
			// rather than emit a COPY that silently fails to build.
			src, dst := localCopyArgs(step.Method, step.Args)
			fmt.Fprintf(&b, "COPY %s %s\n", src, dst)
			rep.Addf(leak.PrimImage, leak.KindSemanticGap, script, 0,
				"image DSL .%s(%s): local path must be staged into the build context; calque does not stage it — the COPY will fail unless %q is present at build time",
				step.Method, quoteJoin(step.Args), src)
		case "run_function":
			// .run_function(fn) runs a Python callable at BUILD time — a fundamentally
			// different execution than a shell RUN (it needs the function + its imports
			// staged and invoked). We can't reproduce that here; leak it, don't fake it.
			rep.Addf(leak.PrimImage, leak.KindSemanticGap, script, 0,
				"image DSL .run_function(...) executes a Python callable at build time; not reproduced (needs the function + deps staged and invoked in the build)")
		default:
			// A DSL verb we don't model. Comment it AND leak it — silent drop would
			// change the runtime environment invisibly (§10).
			fmt.Fprintf(&b, "# UNHANDLED .%s(%s) — see leak report\n", step.Method, quoteJoin(step.Args))
			rep.Addf(leak.PrimImage, leak.KindUnsupportedArg, script, 0,
				"image DSL verb .%s(...) not translated to Dockerfile; environment may differ from Modal", step.Method)
		}
	}

	// Worker glue: the warm runner + warmd supervisor. Copied into the image so
	// the instance runs `warmd` which drives `runner.py` (§6).
	wd := spec.WorkerDir
	if wd == "" {
		wd = "/opt/calque"
	}
	fmt.Fprintf(&b, "COPY runner.py %s/runner.py\n", wd)
	fmt.Fprintf(&b, "COPY warmd %s/warmd\n", wd)
	if spec.EntryCmd != "" {
		fmt.Fprintf(&b, "CMD %s\n", spec.EntryCmd)
	}
	return b.String(), nil
}

func resolveBase(img ir.Image, script string, rep *leak.Report) (string, error) {
	if img.Unresolved || img.Base == "" {
		rep.Add(leak.PrimImage, leak.KindSemanticGap, script, 0,
			"image base unresolved; defaulting to CUDA runtime base — payload deps may be incomplete")
		return baseImages["debian_slim"], nil
	}
	if b, ok := baseImages[img.Base]; ok {
		return b, nil
	}
	// from_registry("nvcr.io/...") names its own base in the first step's args.
	// from_aws_ecr("<acct>.dkr.ecr.<region>.amazonaws.com/repo:tag") likewise names
	// a private ECR image as the base — treat its first arg as the FROM ref.
	for _, s := range img.Steps {
		if (s.Method == "from_registry" || s.Method == "from_aws_ecr") && len(s.Args) > 0 {
			if s.Method == "from_aws_ecr" {
				// The instance role must be able to pull from this ECR repo; note it so
				// a pull-permission failure isn't mistaken for a calque bug (§10).
				rep.Addf(leak.PrimImage, leak.KindIntegrationEdge, script, 0,
					"image base from_aws_ecr(%q): the acquired instance role needs ecr:GetDownloadUrlForLayer / BatchGetImage on this repo to pull", s.Args[0])
			}
			return s.Args[0], nil
		}
		if s.Method == "from_dockerfile" && len(s.Args) > 0 {
			// from_dockerfile(path) names a LOCAL Dockerfile — the closest 1:1
			// mapping to calque's own pipeline, but the referenced file isn't
			// staged by calque (same limitation as add_local_*/copy_local_* — §D,
			// calque#84). We can't inline its content sight-unseen, so leak the
			// requirement rather than silently substitute an unrelated base.
			rep.Addf(leak.PrimImage, leak.KindSemanticGap, script, 0,
				"image base from_dockerfile(%q): calque does not read/stage this local Dockerfile — defaulting to CUDA runtime base; the payload's real base/deps may be missing", s.Args[0])
			return baseImages["debian_slim"], nil
		}
	}
	if img.Base == "micromamba" {
		// calque#84: micromamba() is a real, distinct base (a conda-alternative,
		// not CUDA/debian) — was silently defaulting to CUDA with only a generic
		// "unknown image base" leak. _walk_image_chain only captures POSITIONAL
		// args (tools/pyast/pyast.py), so a kwarg like python_version= is invisible
		// here — leak that limitation too, since the emitted base won't reflect it.
		rep.Addf(leak.PrimImage, leak.KindSemanticGap, script, 0,
			"image base micromamba(...): mapped to %q; any kwargs (e.g. python_version=) are not captured by the parser and are NOT reflected in this base", micromambaBase)
		return micromambaBase, nil
	}
	rep.Addf(leak.PrimImage, leak.KindUnhandledCase, script, 0,
		"unknown image base %q; defaulting to CUDA runtime base", img.Base)
	return baseImages["debian_slim"], nil
}

// localCopyArgs maps an add_local_*/copy_local_* step's args to (src, dst). Modal's
// add_local_dir(local, remote) / add_local_file(local, remote) take two positional
// paths; add_local_python_source(module) takes one (the destination defaults to the
// image's site-packages). We default a missing dst so the emitted COPY is well-formed.
func localCopyArgs(method string, args []string) (src, dst string) {
	switch len(args) {
	case 0:
		return ".", "/"
	case 1:
		if method == "add_local_python_source" {
			return args[0], "/root/" + args[0] // module name -> importable path
		}
		return args[0], "/" + args[0]
	default:
		return args[0], args[1]
	}
}

// leakLocalContext records that a step depends on a file that must be present in
// the build context (A3): a requirements.txt / pyproject.toml calque does not
// stage. The COPY is emitted so intent is preserved, but the build fails loudly if
// the file is absent — better than silently dropping the dependency install.
func leakLocalContext(rep *leak.Report, script, method, path string) {
	rep.Addf(leak.PrimImage, leak.KindSemanticGap, script, 0,
		"image DSL .%s(%q): %q must be in the build context; calque does not stage it", method, path, path)
}

// jsonArrayJoin renders args as a JSON string array body for ENTRYPOINT exec form:
// ["a","b"] -> `"a", "b"`.
func jsonArrayJoin(args []string) string {
	parts := make([]string, len(args))
	for i, a := range args {
		parts[i] = fmt.Sprintf("%q", a)
	}
	return strings.Join(parts, ", ")
}

// Digest is a stable content hash of the Dockerfile text, used as the ECR tag so
// an identical image is a cache hit (build-once, §10). Same Dockerfile => same tag.
func Digest(dockerfile string) string {
	sum := sha256.Sum256([]byte(dockerfile))
	return fmt.Sprintf("%x", sum)[:16]
}

// quoteJoin renders args as a space-joined, shell-safe list. Package names rarely
// need quoting, but a version spec like "torch==2.4.1" is fine unquoted; anything
// with spaces gets quoted.
func quoteJoin(args []string) string {
	cp := append([]string(nil), args...)
	// stable order only for pip-like package lists where order is immaterial to
	// correctness but matters for a reproducible digest.
	if looksLikePackages(cp) {
		sort.Strings(cp)
	}
	parts := make([]string, len(cp))
	for i, a := range cp {
		if strings.ContainsAny(a, " \t\"'") {
			parts[i] = fmt.Sprintf("%q", a)
		} else {
			parts[i] = a
		}
	}
	return strings.Join(parts, " ")
}

func looksLikePackages(args []string) bool {
	for _, a := range args {
		if strings.ContainsAny(a, "/&|;") { // a shell command, not a package
			return false
		}
	}
	return true
}
